config/routes.rb
Rails.application.routes.draw do
  get 'orgs/index'

  get 'orgs/show'

  get 'orgs/new'
 

  post 'orgs/create'

  devise_for :users

  resources :users
  resources :event

  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessor :title
	attr_accessor :location
	attr_accessor :date
	attr_accessor :subject
	attr_accessor :description
end

app/models/org.rb
class Org < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
  end

  def after_update_path_for(resource)
    orgs_index_path
  end

  def after_sign_in_path_for(resource)
    orgs_index_path
  end
  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
	def index
		@events = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)

		@event.save()
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
  end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  layout 'orgs'
  before_action :authenticate_user!

  def index
    @orgs = Org.all.reverse_order
    @events = Event.all.reverse_order()
  end

  def show
    @org = Org.find(:id)
  end

  def new
    @org = Org.new
  end

  def create
    @org = Org.new(org_params)
    if @org.save
      redirect_to orgs_index_path, notice: "New post successfully added"
    else
      render 'new'
    end
  end

  def destroy
    @org = Org.find(params[:id])
    @org.destory
    redirect_to root_path
  end

  private
  def org_params
    params.require(:org).permit(:body, :name, :location)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event/index.html.erb
<% @events.each do |event| %>
   <%= event.title %>
<% end %>

app/views/event/new.html.erb
<%= form_for :event do |f| %>
	Title: <%= f.text_field :title %>
	Location: <%= f.text_field :location %>
	Date: <%= f.text_field :date %>
	Subject: <%= f.text_field :subject %>
	Description: <%= f.text_field :description %>
	<%= f.submit %>
<% end %>

app/views/home/index.html.erb
 <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-size:22px;" href="#">
                	UberTutor
                </a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><%=link_to "Sign Up", new_user_registration_path, class: "btn btn-lg"%></li>
                    <% if !user_signed_in? %>
                        <li> <%=link_to "Log In", new_user_session_path, class: "btn btn-lg" %></li>
                    <% else %>
                      <li> <%= link_to "LOG OUT", destroy_user_session_path, class: "btn btn-lg", :method => :delete %></li>
                    <% end %>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

	<!-- Header -->
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Get Involved</h1>
                <p>Parenteer: Engage in your child's classroom today.</p>
                    <%=link_to "Start Today", new_user_registration_path, class: "btn btn-primary btn-lg"%>
            </div>
        </div>
    </header>

	<!-- Intro Section -->
    <section class="intro">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                	<span class="glyphicon glyphicon-apple" style="font-size: 60px"></span>
                    <h2 class="section-heading">#Swag</h2>
                    <p class="text-dark">Pareenter allows school administrators to request parent volunteers 
for school events. Parents can sign up for an account and suscribe to a school
to receive volunteer requests via text from school admins.</p>
                </div>
            </div>
        </div>
    </section>

		
		<!-- Scripts -->
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ubertutor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ubertutor</title>
  <%= stylesheet_link_tag 'home', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'custom', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.scrollex.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'main', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'skel.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'util', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
<!-- Footer -->
<footer class="page-footer">

  <!-- Contact Us -->
  <div class="contact">
    <div class="container">
      <h2 class="section-heading">Contact Us</h2>
      <p><span class="glyphicon glyphicon-earphone"></span><br> +1(23) 456 7890</p>
      <p><span class="glyphicon glyphicon-envelope"></span><br> info@example.com</p>
    </div>
  </div>

  <!-- Copyright etc -->
  <div class="small-print">
    <div class="container">
      <p>Copyright &copy; Example.com 2015</p>
    </div>
  </div>

</footer>
<!-- jQuery -->
<script src="js/jquery-1.11.3.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="js/jquery.easing.min.js"></script>

<!-- Custom Javascript -->
<script src="js/custom.js"></script>
</html>

app/views/layouts/orgs.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ubertutor</title>
  <%= stylesheet_link_tag    'skel', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style' %>
  <%= stylesheet_link_tag    'style-mobile', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style-narrow', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style-narrower', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style-normal', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style-wide', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'init', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'skel.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'skel-layers.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.dropotron.min', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="description" content="" />

  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
</html>

app/views/orgs/index.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link href="css/style.css" rel="stylesheet" type="text/css"  media="all" />
		<title>User Profile | Feed </title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
		<script type="text/javascript" src="http://jqueryjs.googlecode.com/files/jquery-1.3.1.js"></script>
	</head>
	<body>

			<!-- End-Header-->
			<div class="clear"> </div>
			<!-- content-gallery-->
			</div>
			<div class="wrap" style="border-left: 0.07em solid #3fb1a3; border-right: 0.07em solid #3fb1a3; ">
				<div class="about">
					<div class="services-sidebar">
					<h4></h4>
	
				</div>
					<div class="bloder-content">
						
					<div class="bloger-grid">
						
						<div class="blog-img">
							<%= image_tag 'EdnaBrewer.JPG' %>
						</div>
						<div class="bloger-content">
							<h5 style="font-size: 150%;">Edna Brewer Middle School</h5>
							<p style="font-size: 115%;"> Location:
							</p> 
							<!-- <p style="font-size: 115%;">	Date:
							</p> 
							<p style="font-size: 115%;">	Subject: 
								</p> -->
							<ul>
								<li><a href="#">Request Made</a></li>
								<li><a href="#">: 2 Minutes Ago</a></li>
                                <li><a href="#">: 15 Subscriptions </a></li>
                              <p> <li><a style="background: none;
                                    border: solid 1px #3fb1a3;
                                    color: inherit;
                                    cursor: pointer;
                                    display: inline-block;
                                    font-size: 0.8em;
                                    font-weight: 900;
                                    letter-spacing: 2px;
                                    min-width: 18em;
                                    padding: 0 0.75em;
                                    line-height: 3.75em;
                                    text-align: center;
                                    text-decoration: none;
                                    text-transform: uppercase;" href="#"> Subscribe </a></li> </p>
							</ul>
						</div>
						<div class="clear"> </div>
					</div>
					
					<div class="clear"> </div>
					<div class="bloger-grid">
						<div class="blog-img">
							<%= image_tag 'KippOakland.jpg' %>
						</div>
						<div class="bloger-content">
							
							<h5 style="font-size: 150%;">Kipp King Collegiate Middle School</h5>
							<p style="font-size: 115%;"> Location:
							</p> 
							<!-- <p style="font-size: 115%;">	Date:
							</p> 
							<p style="font-size: 115%;">	Subject: 
								</p> -->
							<ul>
								<li><a href="#">Request Made</a></li>
								<li><a href="#">: 10 Minutes Ago</a></li>
                                <li><a href="#">: 15 Subscriptions </a></li>
                              <p> <li><a style="background: none;
                                    border: solid 1px #3fb1a3;
                                    color: inherit;
                                    cursor: pointer;
                                    display: inline-block;
                                    font-size: 0.8em;
                                    font-weight: 900;
                                    letter-spacing: 2px;
                                    min-width: 18em;
                                    padding: 0 0.75em;
                                    line-height: 3.75em;
                                    text-align: center;
                                    text-decoration: none;
                                    text-transform: uppercase;" href="#"> Subscribe </a></li> </p>
                            </ul>
						</div>
						<div class="clear"> </div>
					</div>
					<div class="clear"> </div>
					<div class="bloger-grid">
						<div class="blog-img">
							<%= image_tag 'LONGFELLOW.jpg' %>
						</div>
						<div class="bloger-content">
							<h5 style="font-size: 150%;">LongFellow Middle School</h5>
							<p style="font-size: 115%;"> Location:
							</p> 
							<!-- <p style="font-size: 115%;">	Date:
							</p> 
							<p style="font-size: 115%;">	Subject: 
								</p> -->
							<ul>
								<li><a href="#">Request Made</a></li>
								<li><a href="#">: 15 Minutes Ago</a></li>
                                <li><a href="#">: 15 Subscriptions </a></li>
                                <p> <li><a style="background: none;
                                    border: solid 1px #3fb1a3;
                                    color: inherit;
                                    cursor: pointer;
                                    display: inline-block;
                                    font-size: 0.8em;
                                    font-weight: 900;
                                    letter-spacing: 2px;
                                    min-width: 18em;
                                    padding: 0 0.75em;
                                    line-height: 3.75em;
                                    text-align: center;
                                    text-decoration: none;
                                    text-transform: uppercase;" href="#"> Subscribe </a></li> </p>

                            </ul>
						</div>
						<div class="clear"> </div>
					</div>
					<div style="border-bottom:none;" class="bloger-grid">
						<div class="blog-img">
							<%= image_tag 'montera.jpg' %>
						</div>
						<div class="bloger-content">
							<h5 style="font-size: 150%;">Montera Middle School</h5>
							<p style="font-size: 115%;"> Location:
							</p> 
							<!-- <p style="font-size: 115%;">	Date:
							</p> 
							<p style="font-size: 115%;">	Subject: 
								</p> -->
							<ul>
								<li><a href="#">Request Made</a></li>
								<li><a href="#">: 20 Minutes Ago</a></li>
                                <li><a href="#">: 15 Subscriptions </a></li>
                                <p> <li><%= link_to "Subscribe", new_event_path, style: "background: none;
                                            border: solid 1px #3fb1a3;
                                            color: inherit;
                                            cursor: pointer;
                                            display: inline-block;
                                            font-size: 0.8em;
                                            font-weight: 900;
                                            letter-spacing: 2px;
                                            min-width: 18em;
                                            padding: 0 0.75em;
                                            line-height: 3.75em;
                                            text-align: center;
                                            text-decoration: none;
                                            text-transform: uppercase;" %></li> </p>
                            </ul>
						
						</div> 
						<div class="clear"> </div>
					</div>
					</div>
					
					<div class="clear"> </div>
				
			</div>
			</div>
			
    <div class="clear"> </div>
			<!-- End-content-gallery-->
			<!-- DC Pagination:C9 Start -->
			<div class="wrap">
	<!-- DC Pagination:A3 Start -->
						<!-- <ul class="dc_pagination dc_paginationA dc_paginationA03">
						  <li><a href="#" class="first">First</a></li>
						  <li><a href="#" class="previous">Previous</a></li>
						  <li><a href="#">1</a></li>
						  <li><a href="#">2</a></li>
						  <li><a href="#" class="current">3</a></li>
						  <li><a href="#">4</a></li>
						  <li><a href="#">5</a></li>
						  <li><a href="#" class="next">Next</a></li>
						  <li><a href="#" class="last">Last</a></li>

						</ul> -->
							<!-- DC Pagination:A3 End -->

	    		<div class="clear"> </div>

	<!-- DC Pagination:C9 End -->

		</div>
	<div class="clear"> </div>
		<!-- <div class="footer">
				<div class="wrap">
				<h3>SAY HELLO</h3>
				<p>Lorem ipsum dolor sit amet, consect etur adipiscing elit. Vestibulum ut tortor urnati dunt

						dolor. Nunc vulputate ultrices con sect etur donec semper lacinia ultri dolore cie

						lorem ipsum commete.</p>

			<div class="footerlinks">
				<div class="share">
		                	<li><a href="#" target="_blank" title="Facebook"><span class="social fbook"> </span></a></li>
		                	<li><a href="#" target="_blank" title="twitter"><span class="social twitter"> </span></a></li>
		                    <li><a href="#" target="_blank" title="tumblr"><span class="social tumblr"> </span></a></li><br />
		                    <li><a href="#" target="_blank" title="delicious"><span class="social delicious"> </span></a></li>
		                	<li><a href="#" target="_blank" title="delicious"><span class="social delicious"> </span></a></li>
		                	<li><a href="#" target="_blank" title="dribbble"><span class="social dribbble"> </span></a></li>
		                    <li><a href="#" target="_blank" title="evernote"><span class="social evernote"> </span></a></li>
		                    <li><a href="#" target="_blank" title="stumbleupon"><span class="social stumbleupon"> </span></a></li>

		                </div>


			</div>
			</div>
			</div>
			<div class="footer1"> -->
	<!-- <p class="link"><span>© All rights Reserved | Designed by&nbsp; <a href="http://w3layouts.com/"> W3Layouts</a>	</span></p> -->
</div>
		<!-- End-wrap -->

	</body>
</html>

app/views/orgs/new.html.erb
<h1>Orgs#new</h1>
<p>Find me in app/views/orgs/new.html.erb</p>

app/views/orgs/show.html.erb
<h1>Orgs#show</h1>
<p>Find me in app/views/orgs/show.html.erb</p>

app/views/users/show.html.erb
<html> 
<h1>This is our news feed! I do not think it works tho. We are working on it.</h1><!-- 
<div style="width: 158px; border: #000000 1px solid; background-color: #339999; text-align: left; padding: 0px 2px 7px 2px; position: absolute; visibility: visible; left: 100px; top: 100px; z-index:3;">
<div style="color: #FFFFFF; font: 13px arial, sans-serif; font-weight: bold; text-align: center; padding: 3px;">
Floating Sample<br>
</div>
<iframe id="NewsWindow" seamless src="news_win.htm" width="700" height="404" marginwidth="0" marginheight="0" frameborder="0" scrolling="yes" style="display: block; margin: 0 auto; padding: 0; border: #000000 1px solid;"></iframe>
</div> -->

<div id="HCB_comment_box"><a href="http://www.htmlcommentbox.com">Comment Box</a> is loading comments...</div>
 <link rel="stylesheet" type="text/css" href="//www.htmlcommentbox.com/static/skins/bootstrap/twitter-bootstrap.css?v=0" />
 <script type="text/javascript" id="hcb"> /*<!--*/ if(!window.hcb_user){hcb_user={};} (function(){var s=document.createElement("script"), l=hcb_user.PAGE || (""+window.location).replace(/'/g,"%27"), h="//www.htmlcommentbox.com";s.setAttribute("type","text/javascript");s.setAttribute("src", h+"/jread?page="+encodeURIComponent(l).replace("+","%2B")+"&opts=16862&num=10&ts=1445691700494");if (typeof s!="undefined") document.getElementsByTagName("head")[0].appendChild(s);})(); /*-->*/ </script>
</html>